### ISSUE TITLE
Add Database Connectivity programs

### ISSUE THREAD

**Issue by shauryauppal** [shauryauppal/PHP-Database-connection#1]

**Comment by faouziamrouche** [comment]
@shauryauppal Could you please explain the issue more clearly (What do you want exactly)?

**Comment by shauryauppal** [comment]
@faouziamrouche check REDME.md it has basic PHP and SQL programs like update table, create table, insertion, alter. I want more such basic programs to be added.

**Comment by palmerhinchliffe** [comment]
I'll work on this

**Comment by shauryauppal** [comment]
@palmerhinchliffe @faouziamrouche you both can work on this. 👍

**Comment by faouziamrouche** [comment]
@shauryauppal I added a Login and modified Readme

**Comment by palmerhinchliffe** [comment]
I modified database4.php to use PDO as it was vulnerable to SQL injection. Can you please test :)

**Comment by younesdiouri** [comment]
@shauryauppal Hello I PR a way to avoid code redundancy through some easy configuration file and also patched all the files with SQL injection vulnerability if you can give a look ;)
